export const FETCH_GATEWAYS_REQUEST = 'FETCH_GATEWAYS_REQUEST'
export const SET_GATEWAYS = 'SET_GATEWAYS'
export const FAIL_GATEWAYS = 'FAIL_GATEWAYS'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const SET_USERS = 'SET_USERS'
export const FAIL_USERS = 'FAIL_USERS'

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST'
export const SET_PROJECTS = 'SET_PROJECTS'
export const FAIL_PROJECTS = 'FAIL_PROJECTS'

export const POST_REPORT_REQUEST = 'POST_REPORT_REQUEST'
export const POST_REPORT = 'POST_REPORT'
export const FAIL_REPORT_POST = 'FAIL_REPORT_POST'